### ISSUE TITLE
Browser issues

### ISSUE THREAD

**Issue by garywood84** [pajasevi/CSSnowflakes#1]
I am trying to use this code but in Microsoft Edge, the biggest snowflakes turn cyan instead of white, and in Safari on macOS, the shadow disappears, so the snowflakes disappear if they pass over anything white.

**Comment by rd18aac** [comment]
Edge uses Microsoft's emojis instead of Google's (in Chrome) or Apple's (in Safari). Microsoft's snowflake emojis are cyan for some weird reason, hence why I hate Microsoft's emojis. To get rid of the cyan snowflakes, just remove the emoji versions of the snowflake in the code and replace them with more of the standard Unicode ones.

The shadow issue would probably be to do with how Safari renders the CSS in it's webkit engine. I haven't used shadows in CSS before so this would probably be a question/problem for someone who knows about CSS shadows.

**Comment by pajasevi** [comment]
@garywood84 Interesting issue, can you provide a screenshot of this behavior?

@robsd Thanks for the info but I find it kind of weird because I used unicode snowflake characters.

I tried Safari and all worked as it should, even the shadow. Maybe you can just adjust it.

**Comment by garywood84** [comment]
@pajasevi Thanks for getting back to me. Please see two screenshots attached: one from Microsoft Edge on Windows (where the biggest snowflakes are cyan); and one from Safari on macOS, where you'll see that the snowflakes have no shadow (which is a problem where there are any white areas on the site).

I hope you can fix it for us! :-)

(Also, if you can fix it, could you tell me how I can increase the number of snowflakes, please?)

![snowflakes-ss-msedge](https://user-images.githubusercontent.com/11328180/49700193-5a82e880-fbd3-11e8-8864-2dbbae189a30.png)

<img width="1440" alt="snowflakes-ss-safari" src="https://user-images.githubusercontent.com/11328180/49700196-5d7dd900-fbd3-11e8-8c98-c0abdc8059ac.png">

**Comment by pajasevi** [comment]
@garywood84 I updated the snippet, hope this will fix it. If you want more snowflakes, just copy&paste `div`s with class `snowflake`.

**Comment by garywood84** [comment]
@pajasevi Thanks for this mate. The colour is now correct in MS Edge, and the shadow appears in Safari. However, in all browsers, the leftmost snowflake appears with a bolder shadow than the rest - almost as if two or more snowflakes are stacked on top of each other (see below). Any ideas what might be causing that?

![image](https://user-images.githubusercontent.com/11328180/49702173-55cb2e00-fbed-11e8-8eee-39bce587ec94.png)

<img width="1440" alt="screenshot 2018-12-09 at 20 01 15" src="https://user-images.githubusercontent.com/11328180/49702174-624f8680-fbed-11e8-9297-3cb96167fa51.png">

**Comment by pajasevi** [comment]
@garywood84 You're right. I Fixed it.

**Comment by rd18aac** [comment]
Looking brill now guys! Updated the snippet on my site www.robertd.co.uk!

**Comment by pajasevi** [comment]
Thanks for your inputs guys, I'm closing this now.

**Comment by garywood84** [comment]
Thanks @pajasevi! Looks perfect, now.

I've tried increasing the number of snowflakes by copying more divs, as you suggested, but when I do this, it seems that they all stack on top of the left-most flake again. Am I doing something wrong?
